export const SET_INFO = 'SET_INFO'
export const SET_ADDLIST = 'SET_ADDLIST'
export const SET_NUM = 'SET_NUM'

export const SET_USER_FRIEND_LIST_CACHE = 'SET_USER_FRIEND_LIST_CACHE'

export const SET_CHAT_LIST_CACHE = 'SET_CHAT_LIST_CACHE'

export const SET_SYSUSER_CIRCLE_OF_FRIENDS_LIST = 'SET_SYSUSER_CIRCLE_OF_FRIENDS_LIST'

export const SET_CIRCLE_NUM = 'SET_CIRCLE_NUM'

export const SET_GROUP_INFO = 'SET_GROUP_INFO'